[package]
name = "AfSuiRule"
version = "0.0.1"
published-at = "0x27bf2ca4789fb5cba4d7a589eb1477202f240e317eddd469744fb685d77ca399"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
BucketOracle = { git = "https://github.com/Bucket-Protocol/oracle.git", rev = "mainnet" }
AftermathLSD = { local = "../../partners/aftermath-interfaces/packages/afsui/afsui-staked-sui-vault" }

[addresses]
afsui_rule = "0x27bf2ca4789fb5cba4d7a589eb1477202f240e317eddd469744fb685d77ca399"
# afsui_rule = "0x0"
