[package]
name = "AfSuiRule"
version = "0.0.1"
published-at = "0x2480d9a3ff2c821061df22c4365316f894c6fa686fbd03ba828fe7c5bef9ad22"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
BucketOracle = { git = "https://github.com/Bucket-Protocol/oracle.git", rev = "mainnet" }
AftermathLSD = { local = "../../partners/aftermath-interfaces/packages/afsui/afsui-staked-sui-vault" }

[addresses]
afsui_rule = "0x2480d9a3ff2c821061df22c4365316f894c6fa686fbd03ba828fe7c5bef9ad22"
# afsui_rule = "0x0"
