[package]
name = "BluefinSpot"
version = "1.0.0"
published-at = "0x6c796c3ab3421a68158e0df18e4657b2827b1f8fed5ed4b82dba9c935988711b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet", override=true }
CetusClmm = { local = "../cetus/clmmpool" }
IntegerMate = { local = "../cetus/integer-mate" }

[addresses]
bluefin_spot = "0x3492c874c1e3b3e2984e8c41b589e642d4d0a5d6459e5a9cfc2d52fd7c89c267"
