[package]
name = "PythLocal"
version = "0.0.1"
published-at = "0x00b53b0f4174108627fbee72e2498b58d6a2714cded53fac537034c220d26302"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

# [dependencies.Wormhole]
# git = "https://github.com/wormhole-foundation/wormhole.git"
# subdir = "sui/wormhole"
# rev = "82d82bffd5a8566e4b5d94be4e4678ad55ab1f4f"
[dependencies]
Wormhole = { git = "https://github.com/naviprotocol/wormhole.git", rev = "navi-forked", subdir = "sui/wormhole" }

[addresses]
pyth_local = "0x00b53b0f4174108627fbee72e2498b58d6a2714cded53fac537034c220d26302"
wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"